Algoritmo "mod"


Var
x, y, quoc, resto: inteiro


Inicio
escreva("Valor de X é: ")
leia(x)

escreval("=================")

escreva("Valor de Y é: ")
leia(y)

quoc <- x div y
resto <- x mod y

escreval("=================")

escreval("O quociente da divisão dos valores informados é: ", quoc)

escreval("==================")

escreval("O resto da divisão dos valores informados é: ", resto)

Fimalgoritmo